// Code generated by MockGen. DO NOT EDIT.
// Source: internal\service\services.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/inggl/erp/storage/internal/model"
)

// MockBucketService is a mock of BucketService interface.
type MockBucketService struct {
	ctrl     *gomock.Controller
	recorder *MockBucketServiceMockRecorder
}

// MockBucketServiceMockRecorder is the mock recorder for MockBucketService.
type MockBucketServiceMockRecorder struct {
	mock *MockBucketService
}

// NewMockBucketService creates a new mock instance.
func NewMockBucketService(ctrl *gomock.Controller) *MockBucketService {
	mock := &MockBucketService{ctrl: ctrl}
	mock.recorder = &MockBucketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketService) EXPECT() *MockBucketServiceMockRecorder {
	return m.recorder
}

// GetBucketFile mocks base method.
func (m *MockBucketService) GetBucketFile(bucketId int) (model.Bucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketFile", bucketId)
	ret0, _ := ret[0].(model.Bucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketFile indicates an expected call of GetBucketFile.
func (mr *MockBucketServiceMockRecorder) GetBucketFile(bucketId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketFile", reflect.TypeOf((*MockBucketService)(nil).GetBucketFile), bucketId)
}

// GetBucketFiles mocks base method.
func (m *MockBucketService) GetBucketFiles() ([]model.Bucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketFiles")
	ret0, _ := ret[0].([]model.Bucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketFiles indicates an expected call of GetBucketFiles.
func (mr *MockBucketServiceMockRecorder) GetBucketFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketFiles", reflect.TypeOf((*MockBucketService)(nil).GetBucketFiles))
}
